### ISSUE TITLE
无法释放 DispatchTimer 类

### ISSUE THREAD

**Issue by JJCrystalForest** [lieryang/DispatchTimer#1]
这个类走不到 dealloc 方法

**Comment by CoderEYLee** [comment]
这个是 C 语言的定时器, 不需要使用的时候, 需要自己释放, 调用cancelTimerWithName:XXX 这个方法。取消对应的定时器

**Comment by JJCrystalForest** [comment]
好的，谢谢，类方法调用的，所以没走dealloc，我还以为是没有销毁




| |
杨馥瑞
邮箱：13702727599@163.com
|

签名由 网易邮箱大师 定制

在2018年07月23日 11:54，CoderEYLee 写道：

这个是 C 语言的定时器, 不需要使用的时候, 需要自己释放, 调用cancelTimerWithName:XXX 这个方法。取消对应的定时器

**Comment by CoderEYLee** [comment]
这个C需要的定时器 程序进去后台也能走定时器方法，自己不需要使用的时候，可以调用取消方法！




| |
李二洋
邮箱：lieryangios@126.com
|

签名由 网易邮箱大师 定制

在2018年07月23日 12:03，CrystalForest 写道：
好的，谢谢，类方法调用的，所以没走dealloc，我还以为是没有销毁




| |
杨馥瑞
邮箱：13702727599@163.com
|

签名由 网易邮箱大师 定制

在2018年07月23日 11:54，CoderEYLee 写道：

这个是 C 语言的定时器, 不需要使用的时候, 需要自己释放, 调用cancelTimerWithName:XXX 这个方法。取消对应的定时器

**Comment by JJCrystalForest** [comment]
好的，谢谢




| |
杨馥瑞
邮箱：13702727599@163.com
|

签名由 网易邮箱大师 定制

在2018年07月23日 12:15，CoderEYLee 写道：
这个C需要的定时器 程序进去后台也能走定时器方法，自己不需要使用的时候，可以调用取消方法！




| |
李二洋
邮箱：lieryangios@126.com
|

签名由 网易邮箱大师 定制

在2018年07月23日 12:03，CrystalForest 写道：
好的，谢谢，类方法调用的，所以没走dealloc，我还以为是没有销毁




| |
杨馥瑞
邮箱：13702727599@163.com
|

签名由 网易邮箱大师 定制

在2018年07月23日 11:54，CoderEYLee 写道：

这个是 C 语言的定时器, 不需要使用的时候, 需要自己释放, 调用cancelTimerWithName:XXX 这个方法。取消对应的定时器
